name: "Cached build"
description: "Setup the build using cache"
inputs:
  ghc:
    description: "Ghc version"
    required: true
  cabal:
    description: "Cabal version"
    required: false
    default: "3.6"
  os:
    description: "Operating system: Linux, Windows or macOS"
    required: true
runs:
  using: "composite"
  steps:
    - uses: haskell/actions/setup@v1
      id: HaskEnvSetup
      with:
        ghc-version  : ${{ inputs.ghc   }}
        cabal-version: ${{ inputs.cabal }}
        enable-stack: false

    - if: inputs.os == 'Windows'
      name: (Windows) Platform config
      run: |
        echo "CABAL_PKGS_DIR=C:\\cabal\\packages" >> $GITHUB_ENV
      shell: bash
    - if: ( inputs.os == 'Linux' ) || ( inputs.os == 'macOS' )
      name: (Linux,macOS) Platform config
      run: |
        echo "CABAL_PKGS_DIR=~/.cabal/packages" >> $GITHUB_ENV
      shell: bash

    # Needs to be before Cache Cabal so the cache can detect changes to the modified cabal.project file
    - if: inputs.ghc == '9.0.1' || inputs.ghc == '9.2.1'
      name: (GHC 9.0/9.2) Use modified `cabal.project`
      env:
        GHCVER: ${{ inputs.ghc }}
      run: |
        # File has some protections preventing regular `rm`.
        # (most probably sticky bit is set on $HOME)
        # `&&` insures `rm -f` return is positive.
        # Many platforms aslo have `alias cp='cp -i'`.
        rm -f -v cabal.project && cp -v cabal-ghc${GHCVER//./}.project cabal.project
      shell: bash

    - if: inputs.os == 'Windows' && inputs.ghc == '8.8.4'
      name: (Windows,GHC 8.8) Modify `cabal.project` to workaround segfaults
      run: |
        echo "package floskell" >> cabal.project
        echo "  ghc-options: -O0" >> cabal.project
      shell: bash

    # Shorten binary names as a workaround for filepath length limits in Windows,
    # but since tests are hardcoded on this workaround -
    # all platforms (in 2021-12-07) need it.
    # All workflows which distinquishes cache on `cabal.project` needs this.
    - name: Workaround shorten binary names
      run: |
        sed -i.bak -e 's/haskell-language-server/hls/g' \
                    -e 's/haskell_language_server/hls/g' \
                    haskell-language-server.cabal cabal.project
        sed -i.bak -e 's/Paths_haskell_language_server/Paths_hls/g' \
                    src/**/*.hs exe/*.hs
      shell: bash

    - name: Retrieving `cabal.project` Hackage timestamp
      run: |
        # Form: index-state: 2021-11-29T08:11:08Z
        INDEX_STATE_ENTRY=$(grep index-state cabal.project)
        # Form: 2021-11-29T08-11-08Z
        INDEX_STATE1=$(echo "$INDEX_STATE_ENTRY" | cut -d' ' -f2 | tr ':' '-')
        echo "INDEX_STATE=$INDEX_STATE1" >> $GITHUB_ENV
      shell: bash

    # We have to restore package sources before `cabal update`
    # because it overwrites the hackage index with the cached one
    - name: Hackage sources cache
      uses: actions/cache@v2
      env:
        cache-name: hackage-sources
      with:
        path:  ${{ env.CABAL_PKGS_DIR }}
        key:   ${{ env.cache-name }}-${{ env.INDEX_STATE }}
        restore-keys: ${{ env.cache-name }}-

    # To ensure we get the lastest hackage index without telying in the haskell action logic
    # It has to be done before `cabal freeze` to make it aware of the new index
    - run: cabal update
      shell: bash

    - name: Form the package list ('cabal.project.freeze')
      run: |
        cabal v2-freeze && \
        echo "" && \
        echo 'Output:' && \
        echo "" && \
        cat 'cabal.project.freeze' && \
        echo "" || \
        echo 'WARNING: Could not produce the `freeze`.'
      shell: bash

    - name: Compiled deps cache
      id: compiled-deps
      uses: actions/cache@v2
      env:
        cache-name: compiled-deps
      with:
        path: ${{ steps.HaskEnvSetup.outputs.cabal-store }}
        key:  ${{ env.cache-name }}-${{ inputs.os }}-${{ inputs.ghc }}-${{ env.INDEX_STATE }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
              ${{ env.cache-name }}-${{ inputs.os }}-${{ inputs.ghc }}-${{ env.INDEX_STATE }}-
              ${{ env.cache-name }}-${{ inputs.os }}-${{ inputs.ghc }}-
              ${{ env.cache-name }}-${{ inputs.os }}-

    # We remove the freeze file cause it could interfere the build
    - name: "Remove freeze file"
      run: rm -f cabal.project.freeze
      shell: bash
