name: HaskellNix

on: [pull_request]
jobs:
  nix:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        ghc: ['ghc8104']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.03
    - uses: cachix/cachix-action@v8
      with:
        name: haskell-nix-language-server
        authToken: ${{ secrets.HLS_NIX_CACHIX_AUTH_TOKEN }}
    - run: nix-shell haskell.nix -A shell --argstr compiler-nix-name ${{ matrix.ghc }} --run "cabal update && cabal build"
